spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tL7mCPugngcSUZmoKop
      secret-key: weO6nCuinXKdoEvGfGMq8fQ5wDRX0e
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: dsm-mail
      application:
        name: dsmail-third-party
      smsconfig:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        appcode: 30de473dd11240e3b3db1a1bc6307720
        tempId: TPL_0000
server:
  port: 30000

