spring:
  redis:
    host: 81.68.107.235
  cache:
    type: redis
    redis:
      time-to-live: 360000
#      key-prefix: CACHE_
      use-key-prefix: true
      cache-null-values: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    username: root
    password: root
    url: jdbc:mysql://101.43.163.178:3306/dsm_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: dsm-product
    application:
      name: dsm-product
    alicloud:
      access-key: LTAI5tL7mCPugngcSUZmoKop
      secret-key: weO6nCuinXKdoEvGfGMq8fQ5wDRX0e
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.c1eye.dsmail: debug
