spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://dsm-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third_party_route
          uri: lb://dsm-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(<?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
