spring:
  redis:
    host: 81.68.107.235
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: dsm-auth
  application:
    name: dsm-auth
  session:
    store-type: redis
    timeout: 10000
server:
  port: 15000
