spring:
  elasticsearch:
    rest:
      uris: [ "http://101.43.163.178:9200" ]
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    username: root
    password: root
    url: jdbc:mysql://101.43.163.178:3306/dsm_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: dsm-search
    application:
      name: dsm-search
server:
  port: 12000
logging:
  level:
    com.c1eye.dsmail: debug

